# Generated by Django 4.2.1 on 2023-06-15 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_rename_address_order_address1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='address1',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='city1',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='email1',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='name1',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='state1',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='zipcode1',
            new_name='zipcode',
        ),
    ]
